name: Automatic build release on tag

on:
  push:
    tags:
      - '*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Zig compiler
        uses: mlugg/setup-zig@v2
        with:
          version: '0.14.1'

      - name: Build for all targets
        run: |
          declare -a targets=(
            "x86_64-windows"
            "aarch64-windows"
            "x86_64-linux"
            "aarch64-linux"
            "x86_64-macos"
            "aarch64-macos"
          )
          mkdir -p artifacts

          rm -r -f /home/runner/.cache/zig
          zig fetch --save git+https://github.com/Hejsil/zig-clap
          
          for tgt in "${targets[@]}"; do
            zig build -Dtarget="$tgt" --release=safe --prefix "zig-out/$tgt"
            binpath="zig-out/$tgt/bin"
            tar -czf "artifacts/zig-wol-${tgt}.tar.gz" -C "$binpath" .
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zig-wol-artifacts
          path: artifacts/*.tar.gz

  release:
    needs: build_and_release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: zig-wol-artifacts
          path: artifacts

      - name: List downloaded artifacts
        run: ls -lh artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: artifacts/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_ONLY_CONTENTS }}
